export interface RegionOption {
  value: string
  label: string
}

export const RUSSIAN_REGIONS: RegionOption[] = [
  { value: 'moscow', label: 'г. Москва' },
  { value: 'spb', label: 'г. Санкт-Петербург' },
  { value: 'adygeya', label: 'Республика Адыгея' },
  { value: 'altai-republic', label: 'Республика Алтай' },
  { value: 'bashkortostan', label: 'Республика Башкортостан' },
  { value: 'buryatia', label: 'Республика Бурятия' },
  { value: 'dagestan', label: 'Республика Дагестан' },
  { value: 'ingushetia', label: 'Республика Ингушетия' },
  { value: 'kbr', label: 'Кабардино-Балкарская Республика' },
  { value: 'kalmykia', label: 'Республика Калмыкия' },
  { value: 'kchr', label: 'Карачаево-Черкесская Республика' },
  { value: 'karelia', label: 'Республика Карелия' },
  { value: 'komi', label: 'Республика Коми' },
  { value: 'crimea', label: 'Республика Крым' },
  { value: 'mari-el', label: 'Республика Марий Эл' },
  { value: 'mordovia', label: 'Республика Мордовия' },
  { value: 'sakha', label: 'Республика Саха (Якутия)' },
  { value: 'north-ossetia', label: 'Республика Северная Осетия — Алания' },
  { value: 'tatarstan', label: 'Республика Татарстан' },
  { value: 'tuva', label: 'Республика Тыва' },
  { value: 'udmurtia', label: 'Удмуртская Республика' },
  { value: 'khakassia', label: 'Республика Хакасия' },
  { value: 'chechnya', label: 'Чеченская Республика' },
  { value: 'chuvashia', label: 'Чувашская Республика' },
  { value: 'altai-krai', label: 'Алтайский край' },
  { value: 'zabaykalsky-krai', label: 'Забайкальский край' },
  { value: 'kamchatka-krai', label: 'Камчатский край' },
  { value: 'krasnodar-krai', label: 'Краснодарский край' },
  { value: 'krasnoyarsk-krai', label: 'Красноярский край' },
  { value: 'perm-krai', label: 'Пермский край' },
  { value: 'primorsky-krai', label: 'Приморский край' },
  { value: 'stavropol-krai', label: 'Ставропольский край' },
  { value: 'khabarovsk-krai', label: 'Хабаровский край' },
  { value: 'amur-oblast', label: 'Амурская область' },
  { value: 'arkhangelsk-oblast', label: 'Архангельская область' },
  { value: 'astrakhan-oblast', label: 'Астраханская область' },
  { value: 'belgorod-oblast', label: 'Белгородская область' },
  { value: 'bryansk-oblast', label: 'Брянская область' },
  { value: 'vladimir-oblast', label: 'Владимирская область' },
  { value: 'volgograd-oblast', label: 'Волгоградская область' },
  { value: 'vologda-oblast', label: 'Вологодская область' },
  { value: 'voronezh-oblast', label: 'Воронежская область' },
  { value: 'ivanovo-oblast', label: 'Ивановская область' },
  { value: 'irkutsk-oblast', label: 'Иркутская область' },
  { value: 'kaliningrad-oblast', label: 'Калининградская область' },
  { value: 'kaluga-oblast', label: 'Калужская область' },
  { value: 'kemerovo-oblast', label: 'Кемеровская область' },
  { value: 'kirov-oblast', label: 'Кировская область' },
  { value: 'kostroma-oblast', label: 'Костромская область' },
  { value: 'kurgan-oblast', label: 'Курганская область' },
  { value: 'kursk-oblast', label: 'Курская область' },
  { value: 'leningrad-oblast', label: 'Ленинградская область' },
  { value: 'lipetsk-oblast', label: 'Липецкая область' },
  { value: 'magadan-oblast', label: 'Магаданская область' },
  { value: 'moscow-oblast', label: 'Московская область' },
  { value: 'murmansk-oblast', label: 'Мурманская область' },
  { value: 'nizhny-novgorod-oblast', label: 'Нижегородская область' },
  { value: 'novgorod-oblast', label: 'Новгородская область' },
  { value: 'novosibirsk-oblast', label: 'Новосибирская область' },
  { value: 'omsk-oblast', label: 'Омская область' },
  { value: 'orenburg-oblast', label: 'Оренбургская область' },
  { value: 'orel-oblast', label: 'Орловская область' },
  { value: 'penza-oblast', label: 'Пензенская область' },
  { value: 'pskov-oblast', label: 'Псковская область' },
  { value: 'rostov-oblast', label: 'Ростовская область' },
  { value: 'ryazan-oblast', label: 'Рязанская область' },
  { value: 'samara-oblast', label: 'Самарская область' },
  { value: 'saratov-oblast', label: 'Саратовская область' },
  { value: 'sakhalin-oblast', label: 'Сахалинская область' },
  { value: 'sverdlovsk-oblast', label: 'Свердловская область' },
  { value: 'smolensk-oblast', label: 'Смоленская область' },
  { value: 'tambov-oblast', label: 'Тамбовская область' },
  { value: 'tver-oblast', label: 'Тверская область' },
  { value: 'tomsk-oblast', label: 'Томская область' },
  { value: 'tula-oblast', label: 'Тульская область' },
  { value: 'tyumen-oblast', label: 'Тюменская область' },
  { value: 'ulyanovsk-oblast', label: 'Ульяновская область' },
  { value: 'chelyabinsk-oblast', label: 'Челябинская область' },
  { value: 'yaroslavl-oblast', label: 'Ярославская область' },
  { value: 'jewish-ao', label: 'Еврейская автономная область' },
  { value: 'nenets-ao', label: 'Ненецкий автономный округ' },
  { value: 'khanty-mansi-ao', label: 'Ханты-Мансийский автономный округ — Югра' },
  { value: 'chukotka-ao', label: 'Чукотский автономный округ' },
  { value: 'yamalo-nenets-ao', label: 'Ямало-Ненецкий автономный округ' },
  { value: 'sevastopol', label: 'г. Севастополь' },
]
